CREATE TABLE `cte_download_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`clienteId` int NOT NULL,
	`contabilidadeId` int NOT NULL,
	`clienteNome` varchar(255),
	`clienteCnpj` varchar(18),
	`tipo` enum('manual','agendado') NOT NULL DEFAULT 'manual',
	`status` enum('pendente','executando','concluido','erro','cancelado','retomando') NOT NULL DEFAULT 'pendente',
	`totalCtes` int DEFAULT 0,
	`ctesNovos` int DEFAULT 0,
	`progresso` int DEFAULT 0,
	`totalEsperado` int DEFAULT 0,
	`ultimoNsu` bigint DEFAULT 0,
	`certificadoVencido` boolean DEFAULT false,
	`tentativas` int DEFAULT 0,
	`etapa` varchar(255),
	`erro` text,
	`iniciadoEm` timestamp DEFAULT (now()),
	`finalizadoEm` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `cte_download_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `cte_notas` (
	`id` int AUTO_INCREMENT NOT NULL,
	`clienteId` int NOT NULL,
	`contabilidadeId` int NOT NULL,
	`chaveAcesso` varchar(60) NOT NULL,
	`nsu` bigint,
	`numeroCte` varchar(20),
	`serie` varchar(10),
	`modelo` varchar(5),
	`tipoDocumento` enum('CTE','CTE_OS','GTVE','CTE_SIMP','EVENTO') NOT NULL,
	`tipoEvento` varchar(100),
	`direcao` enum('emitido','tomado','terceiro') NOT NULL DEFAULT 'tomado',
	`status` enum('autorizado','cancelado','denegado') NOT NULL DEFAULT 'autorizado',
	`emitenteCnpj` varchar(18),
	`emitenteNome` varchar(255),
	`emitenteUf` varchar(2),
	`remetenteCnpj` varchar(18),
	`remetenteNome` varchar(255),
	`destinatarioCnpj` varchar(18),
	`destinatarioNome` varchar(255),
	`tomadorCnpj` varchar(18),
	`tomadorNome` varchar(255),
	`valorTotal` decimal(15,2),
	`valorReceber` decimal(15,2),
	`valorICMS` decimal(15,2),
	`cfop` varchar(10),
	`natOp` varchar(255),
	`modal` enum('rodoviario','aereo','aquaviario','ferroviario','dutoviario','multimodal'),
	`ufInicio` varchar(2),
	`ufFim` varchar(2),
	`munInicio` varchar(100),
	`munFim` varchar(100),
	`dataEmissao` timestamp,
	`xmlOriginal` text,
	`dactePdfUrl` varchar(512),
	`dactePdfKey` varchar(255),
	`dataDownload` timestamp DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cte_notas_id` PRIMARY KEY(`id`),
	CONSTRAINT `cte_notas_chaveAcesso_unique` UNIQUE(`chaveAcesso`)
);
--> statement-breakpoint
CREATE TABLE `cte_nsu_control` (
	`id` int AUTO_INCREMENT NOT NULL,
	`clienteId` int NOT NULL,
	`contabilidadeId` int NOT NULL,
	`cnpj` varchar(18) NOT NULL,
	`ultimoNsu` bigint NOT NULL DEFAULT 0,
	`maxNsu` bigint NOT NULL DEFAULT 0,
	`ultimaConsulta` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cte_nsu_control_id` PRIMARY KEY(`id`)
);
